// This file contains placeholder data that you'll be replacing with real data in the Data Fetching chapter:

import { Battle, CharacterItem } from "@prisma/client";

// https://nextjs.org/learn/dashboard-app/fetching-data
const users = [
  {
    id: "410544b2-4001-4271-9855-fec4b6a6442a",
    name: "User",
    username: "test",
    password: "123456",
  },
];

const items: CharacterItem[] = [
  {
    createdAt: new Date(),
    firstName: "Edward",
    id: "11",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b11-TA5Nuk7EDUZG.jpg",
    lastName: "Elric",
    origin: "Fullmetal Alchemist",
  },
  {
    createdAt: new Date(),
    firstName: "Faye",
    id: "2",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b2-0Iszg6Izgt4p.png",
    lastName: "Valentine",
    origin: "Cowboy Bebop",
  },
  {
    createdAt: new Date(),
    firstName: "Mitsukuni",
    id: "20",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b20-VNIsuFhxyiJu.png",
    lastName: "Haninozuka",
    origin: "Ouran High School Host Club",
  },
  {
    createdAt: new Date(),
    firstName: "Jet",
    id: "3",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b3-JjH9Si9UM1NZ.png",
    lastName: "Black",
    origin: "Cowboy Bebop",
  },
  {
    createdAt: new Date(),
    firstName: "Naruto",
    id: "17",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b17-IazKGogQwJ1p.png",
    lastName: "Uzumaki",
    origin: "Naruto",
  },
  {
    createdAt: new Date(),
    firstName: "Spike",
    id: "1",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b1-ChxaldmieFlQ.png",
    lastName: "Spiegel",
    origin: "Cowboy Bebop",
  },
  {
    createdAt: new Date(),
    firstName: "Rukia",
    id: "6",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b6-25WoBeWMZXBc.png",
    lastName: "Kuchiki",
    origin: "Bleach",
  },
  {
    createdAt: new Date(),
    firstName: "Sasuke",
    id: "13",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b13-SISLEw1oAD7a.png",
    lastName: "Uchiha",
    origin: "Naruto",
  },
  {
    createdAt: new Date(),
    firstName: "Haruhi",
    id: "18",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b18-SAz5kAo2Fhm1.png",
    lastName: "Fujioka",
    origin: "Ouran High School Host Club",
  },
  {
    createdAt: new Date(),
    firstName: "Ichigo",
    id: "5",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b5-RxGEMJZLW4cy.png",
    lastName: "Kurosaki",
    origin: "Bleach",
  },
  {
    createdAt: new Date(),
    firstName: "Orihime",
    id: "7",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b7-JdR4betokDjR.jpg",
    lastName: "Inoue",
    origin: "Bleach",
  },
  {
    createdAt: new Date(),
    firstName: "Itachi",
    id: "14",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b14-9Kb1E5oel1ke.png",
    lastName: "Uchiha",
    origin: "Naruto",
  },
  {
    createdAt: new Date(),
    firstName: "Alphonse",
    id: "12",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b12-tCKu8yK5kFL5.jpg",
    lastName: "Elric",
    origin: "Fullmetal Alchemist",
  },
  {
    createdAt: new Date(),
    firstName: "Edward",
    id: "16",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b16-80wd87nl1Rue.png",
    lastName: "Wong Hau Pepelu Tivrusky IV",
    origin: "Cowboy Bebop",
  },
  {
    createdAt: new Date(),
    firstName: "Ippo",
    id: "15",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b15-AAj73hDX9bor.jpg",
    lastName: "Makunouchi",
    origin: "Hajime no Ippo: The Fighting!",
  },
  {
    createdAt: new Date(),
    firstName: "Tamaki",
    id: "19",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b19-7Ot7WSWZ7LKF.png",
    lastName: "Suou",
    origin: "Ouran High School Host Club",
  },
  {
    createdAt: new Date(),
    firstName: "Itsuki",
    id: "254",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b254-ZyIHZUY6yz4W.png",
    lastName: "Koizumi",
    origin: "The Disappearance of Haruhi Suzumiya",
  },
  {
    createdAt: new Date(),
    firstName: "Tetsuo",
    id: "96",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b96-qPZIreUZBS5O.jpg",
    lastName: "Kaga",
    origin: "Hikaru no Go",
  },
  {
    createdAt: new Date(),
    firstName: "Akio",
    id: "749",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b749-Aq8jqC8BTwaT.jpg",
    lastName: "Ootori",
    origin: "Revolutionary Girl Utena",
  },
  {
    createdAt: new Date(),
    firstName: "Kentarou",
    id: "971",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b971-kD37ADDZJkV5.png",
    lastName: "Nara",
    origin: "School Rumble",
  },
  {
    createdAt: new Date(),
    firstName: "Saki",
    id: "376",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b376-gDdhShL8BIVg.jpg",
    lastName: "Hanajima",
    origin: "Fruits Basket",
  },
  {
    createdAt: new Date(),
    firstName: "Pete",
    id: "176",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b176-7Lh7NN1tUOzX.png",
    lastName: "Pumps",
    origin: "Skating Rink Kaleidoscope",
  },
  {
    createdAt: new Date(),
    firstName: "Riku",
    id: "960",
    image: "https://s4.anilist.co/file/anilistcdn/character/medium/960.jpg",
    lastName: "Aoba",
    origin: "Tokimeki Memorial",
  },
  {
    createdAt: new Date(),
    firstName: "Duo",
    id: "103",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b103-noYxGpqgx4e0.png",
    lastName: "Maxwell",
    origin: "Mobile Suit Gundam Wing",
  },
  {
    createdAt: new Date(),
    firstName: "Shinobu",
    id: "352",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b352-52C4b1HNO0A8.jpg",
    lastName: "Morita",
    origin: "Honey and Clover II",
  },
  {
    createdAt: new Date(),
    firstName: "Ayame",
    id: "370",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b370-cdEW33vBsXBL.png",
    lastName: "Souma",
    origin: "Fruits Basket",
  },
  {
    createdAt: new Date(),
    firstName: "Kunimitsu",
    id: "325",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b325-vajOILhvy9Vb.png",
    lastName: "Tezuka",
    origin: "Prince of Tennis II",
  },
  {
    createdAt: new Date(),
    firstName: "Grigori",
    id: "863",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b863-lwNK6ZrsXe9q.png",
    lastName: "Efimovich Rasputin",
    origin: "Blood+",
  },
  {
    createdAt: new Date(),
    firstName: "Uryuu",
    id: "564",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b564-a6LJitrjSfKC.jpg",
    lastName: "Ishida",
    origin: "Bleach",
  },
  {
    createdAt: new Date(),
    firstName: "Tomari",
    id: "682",
    image: "https://s4.anilist.co/file/anilistcdn/character/medium/682.jpg",
    lastName: "Kurusu",
    origin: "Girl Meets Girl",
  },
  {
    createdAt: new Date(),
    firstName: "Keiichi",
    id: "885",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b885-t1kV4WAjudpH.png",
    lastName: "Tamaru",
    origin: "The Melancholy of Haruhi Suzumiya",
  },
  {
    createdAt: new Date(),
    firstName: "Chopper",
    id: "309",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/n309-Px56UsWX35A3.jpg",
    lastName: "Tony Tony",
    origin: "ONE PIECE",
  },
  {
    createdAt: new Date(),
    firstName: "Sakurako",
    id: "995",
    image: "https://s4.anilist.co/file/anilistcdn/character/medium/995.jpg",
    lastName: "Shiina",
    origin: "Negima!",
  },
  {
    createdAt: new Date(),
    firstName: "Itoko",
    id: "969",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b969-F7KMmItDjm4i.png",
    lastName: "Osakabe",
    origin: "School Rumble",
  },
  {
    createdAt: new Date(),
    firstName: "Yukio",
    id: "582",
    image: "https://s4.anilist.co/file/anilistcdn/character/medium/582.jpg",
    lastName: "Haibara",
    origin: "Mahoraba ~HeartfuL days~",
  },
  {
    createdAt: new Date(),
    firstName: "Aika",
    id: "380",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b380-ulDFBnzGg2wy.png",
    lastName: "Granzchesta",
    origin: "ARIA The ANIMATION",
  },
  {
    createdAt: new Date(),
    firstName: "Ayla Veverská",
    id: "482",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b482-Pa95YiIaoaJy.png",
    lastName: "Roznovsky",
    origin: "Battle Athletes Victory",
  },
  {
    createdAt: new Date(),
    firstName: "Setsuna",
    id: "744",
    image: "https://s4.anilist.co/file/anilistcdn/character/medium/744.jpg",
    lastName: "Sakurazaki",
    origin: "Negima!",
  },
  {
    createdAt: new Date(),
    firstName: "Maki",
    id: "476",
    image: "https://s4.anilist.co/file/anilistcdn/character/medium/476.jpg",
    lastName: "Tokitou",
    origin: "Karin: Chibi Vampire",
  },
  {
    createdAt: new Date(),
    firstName: "Natsue",
    id: "557",
    image: "https://s4.anilist.co/file/anilistcdn/character/medium/557.jpg",
    lastName: "Awayuki",
    origin: "Prétear: The New Legend of Snow White",
  },
  {
    createdAt: new Date(),
    firstName: "Anna",
    id: "720",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b720-VFo5SzZsVfzl.png",
    lastName: "Liebert",
    origin: "Monster",
  },
  {
    createdAt: new Date(),
    firstName: "Haruie",
    id: "240",
    image: "https://s4.anilist.co/file/anilistcdn/character/medium/240.jpg",
    lastName: "Kakizaki",
    origin: "Mirage of Blaze",
  },
  {
    createdAt: new Date(),
    firstName: "Layla",
    id: "774",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b774-k6TzGmDNwaO6.jpg",
    lastName: "Hamilton",
    origin: "Kaleido Star",
  },
  {
    createdAt: new Date(),
    firstName: "Ken",
    id: "213",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b213-JSjTxWIq6iIt.jpg",
    lastName: "Hidaka",
    origin: "Knight Hunters",
  },
  {
    createdAt: new Date(),
    firstName: "Gokuu",
    id: "246",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/246-wsRRr6z1kii8.png",
    lastName: "Son",
    origin: "Dragon Ball Z",
  },
  {
    createdAt: new Date(),
    firstName: "Ren",
    id: "473",
    image: "https://s4.anilist.co/file/anilistcdn/character/medium/473.jpg",
    lastName: "Maaka",
    origin: "Karin: Chibi Vampire",
  },
  {
    createdAt: new Date(),
    firstName: "Negi",
    id: "146",
    image: "https://s4.anilist.co/file/anilistcdn/character/medium/146.jpg",
    lastName: "Springfield",
    origin: "Negima!",
  },
  {
    createdAt: new Date(),
    firstName: "Ryouko",
    id: "255",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b255-25bilUoTq5HF.png",
    lastName: "Asakura",
    origin: "The Disappearance of Haruhi Suzumiya",
  },
  {
    createdAt: new Date(),
    firstName: "Ushimitsu",
    id: "592",
    image: "https://s4.anilist.co/file/anilistcdn/character/medium/592.jpg",
    lastName: "Minazuki",
    origin: "Mahoraba ~HeartfuL days~",
  },
  {
    createdAt: new Date(),
    firstName: "Winia",
    id: "279",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b279-4FJJvKKMzvQw.png",
    lastName: "Chester",
    origin: "Scrapped Princess",
  },
  {
    createdAt: new Date(),
    firstName: "Gintoki",
    id: "672",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b672-gqeWnyXzOjyX.png",
    lastName: "Sakata",
    origin: "Gintama",
  },
  {
    createdAt: new Date(),
    firstName: "Ginta",
    id: "675",
    image: "https://s4.anilist.co/file/anilistcdn/character/medium/675.jpg",
    lastName: "Toramizu",
    origin: "Marchen Awakens Romance",
  },
  {
    createdAt: new Date(),
    firstName: "Claude K.",
    id: "700",
    image: "https://s4.anilist.co/file/anilistcdn/character/medium/700.jpg",
    lastName: "Winchester",
    origin: "Gravitation TV",
  },
  {
    createdAt: new Date(),
    firstName: "Corkus",
    id: "599",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b599-bzDp9ze9vxFb.png",
    lastName: "",
    origin: "Berserk",
  },
  {
    createdAt: new Date(),
    firstName: "Takeshi",
    id: "331",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b331-9d7jVSiiPUXE.jpg",
    lastName: "Momoshiro",
    origin: "Prince of Tennis II",
  },
  {
    createdAt: new Date(),
    firstName: "Kazuya",
    id: "876",
    image: "https://s4.anilist.co/file/anilistcdn/character/medium/876.jpg",
    lastName: "Kurauchi",
    origin: "My-HiME",
  },
  {
    createdAt: new Date(),
    firstName: "Heinrich",
    id: "721",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b721-VSOxZHBedxtD.png",
    lastName: "Lunge",
    origin: "Monster",
  },
  {
    createdAt: new Date(),
    firstName: "Erika",
    id: "588",
    image: "https://s4.anilist.co/file/anilistcdn/character/medium/588.jpg",
    lastName: "Vermillion",
    origin: "Mahoraba ~HeartfuL days~",
  },
  {
    createdAt: new Date(),
    firstName: "Tsukasa",
    id: "963",
    image: "https://s4.anilist.co/file/anilistcdn/character/medium/963.jpg",
    lastName: "Kasuga",
    origin: "Tokimeki Memorial",
  },
  {
    createdAt: new Date(),
    firstName: "Souji",
    id: "161",
    image: "https://s4.anilist.co/file/anilistcdn/character/medium/161.jpg",
    lastName: "Okita",
    origin: "Peacemaker",
  },
  {
    createdAt: new Date(),
    firstName: "Yuko",
    id: "535",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b535-uSIa1N3IkdMz.png",
    lastName: "Harada",
    origin: "Whisper of the Heart",
  },
  {
    createdAt: new Date(),
    firstName: "Meryl",
    id: "713",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b713-ARN91UwGfe3A.jpg",
    lastName: "Stryfe",
    origin: "Trigun: Badlands Rumble",
  },
  {
    createdAt: new Date(),
    firstName: "Ginji",
    id: "47",
    image: "https://s4.anilist.co/file/anilistcdn/character/medium/47.jpg",
    lastName: "Amano",
    origin: "GetBackers",
  },
  {
    createdAt: new Date(),
    firstName: "Kahoru",
    id: "689",
    image: "https://s4.anilist.co/file/anilistcdn/character/medium/689.jpg",
    lastName: "Osaragi",
    origin: "Girl Meets Girl",
  },
  {
    createdAt: new Date(),
    firstName: "Alice",
    id: "382",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b382-vEjUZDfwwsdY.png",
    lastName: "Carroll",
    origin: "ARIA The ANIMATION",
  },
  {
    createdAt: new Date(),
    firstName: "Teruo",
    id: "800",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b800-lI1hJWbku6V3.png",
    lastName: "Kumai",
    origin: "The Gokusen",
  },
  {
    createdAt: new Date(),
    firstName: "Fuu",
    id: "520",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b520-saKwduKX3WEx.png",
    lastName: "Hououji",
    origin: "Magic Knight Rayearth",
  },
  {
    createdAt: new Date(),
    firstName: "Sousuke",
    id: "402",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b402-4qu9wqpYG8pJ.png",
    lastName: "Kawara",
    origin: "Samurai Champloo",
  },
  {
    createdAt: new Date(),
    firstName: "Haydée",
    id: "420",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b420-Rm5S1bXpT6if.png",
    lastName: "Tebelin",
    origin: "Gankutsuou: The Count of Monte Cristo",
  },
  {
    createdAt: new Date(),
    firstName: "Shinpachi",
    id: "673",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b673-omeYXvqwrNwL.jpg",
    lastName: "Shimura",
    origin: "Gintama",
  },
  {
    createdAt: new Date(),
    firstName: "Anna",
    id: "170",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b170-sQGhuNQ1g3HG.png",
    lastName: "Kyouyama",
    origin: "Shaman King",
  },
  {
    createdAt: new Date(),
    firstName: "Natsumi",
    id: "51",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b51-YA654IlW07lA.jpg",
    lastName: "Mizuki",
    origin: "GetBackers",
  },
  {
    createdAt: new Date(),
    firstName: "Itta",
    id: "976",
    image: "https://s4.anilist.co/file/anilistcdn/character/medium/976.jpg",
    lastName: "Suzuki",
    origin: "Tokimeki Memorial",
  },
  {
    createdAt: new Date(),
    firstName: "Eiji",
    id: "328",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b328-MNfPxc9dhO1e.jpg",
    lastName: "Kikumaru",
    origin: "Prince of Tennis II",
  },
  {
    createdAt: new Date(),
    firstName: "Yuzuru",
    id: "511",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b511-e4pPlBTnMqC5.png",
    lastName: "Narita",
    origin: "Mirage of Blaze",
  },
  {
    createdAt: new Date(),
    firstName: "Sarah",
    id: "877",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b877-XzDsO5BuejlJ.jpg",
    lastName: "Dupont",
    origin: "Kaleido Star",
  },
  {
    createdAt: new Date(),
    firstName: "Shizuru",
    id: "365",
    image: "https://s4.anilist.co/file/anilistcdn/character/medium/365.jpg",
    lastName: "Viola",
    origin: "My-Otome",
  },
  {
    createdAt: new Date(),
    firstName: "Omi",
    id: "212",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b212-fMFyArxjimxF.jpg",
    lastName: "Tsukiyono",
    origin: "Knight Hunters",
  },
  {
    createdAt: new Date(),
    firstName: "Akira",
    id: "515",
    image: "https://s4.anilist.co/file/anilistcdn/character/medium/515.jpg",
    lastName: "Sakamoto",
    origin: "Princess Princess",
  },
  {
    createdAt: new Date(),
    firstName: "Recca",
    id: "189",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b189-sCg8szS0hIaw.jpg",
    lastName: "Hanabishi",
    origin: "Flame of Recca",
  },
  {
    createdAt: new Date(),
    firstName: "Robin",
    id: "61",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b61-YQmTA6SO0UuV.png",
    lastName: "Nico",
    origin: "ONE PIECE",
  },
  {
    createdAt: new Date(),
    firstName: "Yuzuriha",
    id: "438",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b438-0jt2A8eCw9H4.png",
    lastName: "Nekoi",
    origin: "Tsubasa: Tokyo Revelations",
  },
  {
    createdAt: new Date(),
    firstName: "Gorobei",
    id: "155",
    image: "https://s4.anilist.co/file/anilistcdn/character/medium/155.jpg",
    lastName: "Katayama",
    origin: "Samurai 7",
  },
  {
    createdAt: new Date(),
    firstName: "Kenshin",
    id: "147",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b147-miunGYp6fkzb.png",
    lastName: "Himura",
    origin: "Samurai X DVD-BOX Special Ending",
  },
  {
    createdAt: new Date(),
    firstName: "Rikiei",
    id: "399",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b399-fLwLMCgNEXCM.png",
    lastName: "Nagatomi",
    origin: "Samurai Champloo",
  },
  {
    createdAt: new Date(),
    firstName: "Lunamaria",
    id: "120",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b120-8YVoL3Gsvpv8.png",
    lastName: "Hawke",
    origin: "Mobile Suit Gundam Seed Destiny",
  },
  {
    createdAt: new Date(),
    firstName: "Jan",
    id: "621",
    image: "https://s4.anilist.co/file/anilistcdn/character/medium/621.jpg",
    lastName: "Valentine",
    origin: "Hellsing",
  },
  {
    createdAt: new Date(),
    firstName: "Tomonoshin",
    id: "394",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b394-Hq6Bjr5NQ3tU.png",
    lastName: "Shibui",
    origin: "Samurai Champloo",
  },
  {
    createdAt: new Date(),
    firstName: "Yukino",
    id: "357",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b357-fuAAJkjfndpS.jpg",
    lastName: "Miyazawa",
    origin: "His and Her Circumstances",
  },
  {
    createdAt: new Date(),
    firstName: "Ryujirou",
    id: "395",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b395-Jhok5avYsO49.png",
    lastName: "Sasaki",
    origin: "Samurai Champloo",
  },
  {
    createdAt: new Date(),
    firstName: "Mother",
    id: "859",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b859-9HO6zTeTUjBX.png",
    lastName: "Kinjou",
    origin: "Blood+",
  },
  {
    createdAt: new Date(),
    firstName: "Aston",
    id: "872",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b872-mAQXXcCiwuW6.png",
    lastName: "Collins",
    origin: "Blood+",
  },
  {
    createdAt: new Date(),
    firstName: "Ted A.",
    id: "860",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b860-TQaevQX5VdhW.png",
    lastName: "Adams",
    origin: "Blood+",
  },
  {
    createdAt: new Date(),
    firstName: "Yuki",
    id: "208",
    image:
      "https://s4.anilist.co/file/anilistcdn/character/medium/b208-5TmAqqh82wNe.png",
    lastName: "Souma",
    origin: "Fruits Basket",
  },
  {
    createdAt: new Date(),
    firstName: "Hidetada",
    id: "488",
    image: "https://s4.anilist.co/file/anilistcdn/character/medium/488.jpg",
    lastName: "Tokugawa",
    origin: "Samurai Deeper Kyo",
  },
];

const battles: Battle[] = [
  {
    createdAt: new Date(),
    itemOneId: "3",
    itemOneVotes: 138,
    itemTwoId: "4",
    itemTwoVotes: 120,
  },
  {
    createdAt: new Date(),
    itemOneId: "123",
    itemOneVotes: 2,
    itemTwoId: "124",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "1252",
    itemOneVotes: 1,
    itemTwoId: "2245",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "951",
    itemOneVotes: 1,
    itemTwoId: "423",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "197",
    itemOneVotes: 1,
    itemTwoId: "130",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "394",
    itemOneVotes: 0,
    itemTwoId: "799",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "482",
    itemOneVotes: 0,
    itemTwoId: "909",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "716",
    itemOneVotes: 0,
    itemTwoId: "703",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "657",
    itemOneVotes: 1,
    itemTwoId: "822",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "397",
    itemOneVotes: 0,
    itemTwoId: "57",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "768",
    itemOneVotes: 0,
    itemTwoId: "519",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "556",
    itemOneVotes: 1,
    itemTwoId: "514",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "893",
    itemOneVotes: 1,
    itemTwoId: "276",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "358",
    itemOneVotes: 1,
    itemTwoId: "182",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "390",
    itemOneVotes: 1,
    itemTwoId: "844",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "970",
    itemOneVotes: 0,
    itemTwoId: "272",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "93",
    itemOneVotes: 1,
    itemTwoId: "455",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "64",
    itemOneVotes: 0,
    itemTwoId: "913",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "880",
    itemOneVotes: 1,
    itemTwoId: "216",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "478",
    itemOneVotes: 1,
    itemTwoId: "562",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "174",
    itemOneVotes: 1,
    itemTwoId: "334",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "68",
    itemOneVotes: 1,
    itemTwoId: "687",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "978",
    itemOneVotes: 0,
    itemTwoId: "61",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "524",
    itemOneVotes: 0,
    itemTwoId: "629",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "62",
    itemOneVotes: 1,
    itemTwoId: "296",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "43",
    itemOneVotes: 1,
    itemTwoId: "894",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "134",
    itemOneVotes: 0,
    itemTwoId: "19",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "199",
    itemOneVotes: 1,
    itemTwoId: "101",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "7",
    itemOneVotes: 1,
    itemTwoId: "894",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "6",
    itemOneVotes: 2,
    itemTwoId: "3",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "7",
    itemOneVotes: 1,
    itemTwoId: "6",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "1",
    itemOneVotes: 1,
    itemTwoId: "4",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "2",
    itemOneVotes: 1,
    itemTwoId: "6",
    itemTwoVotes: 2,
  },
  {
    createdAt: new Date(),
    itemOneId: "4",
    itemOneVotes: 0,
    itemTwoId: "1",
    itemTwoVotes: 4,
  },
  {
    createdAt: new Date(),
    itemOneId: "4",
    itemOneVotes: 0,
    itemTwoId: "5",
    itemTwoVotes: 2,
  },
  {
    createdAt: new Date(),
    itemOneId: "1",
    itemOneVotes: 2,
    itemTwoId: "1",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "1",
    itemOneVotes: 3,
    itemTwoId: "3",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "7",
    itemOneVotes: 1,
    itemTwoId: "5",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "1",
    itemOneVotes: 2,
    itemTwoId: "6",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "3",
    itemOneVotes: 0,
    itemTwoId: "1",
    itemTwoVotes: 2,
  },
  {
    createdAt: new Date(),
    itemOneId: "1",
    itemOneVotes: 0,
    itemTwoId: "5",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "3",
    itemOneVotes: 0,
    itemTwoId: "7",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "1",
    itemOneVotes: 2,
    itemTwoId: "2",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "3",
    itemOneVotes: 1,
    itemTwoId: "6",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "4",
    itemOneVotes: 0,
    itemTwoId: "6",
    itemTwoVotes: 2,
  },
  {
    createdAt: new Date(),
    itemOneId: "2",
    itemOneVotes: 1,
    itemTwoId: "4",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "6",
    itemOneVotes: 1,
    itemTwoId: "6",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "4",
    itemOneVotes: 0,
    itemTwoId: "2",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "7",
    itemOneVotes: 2,
    itemTwoId: "3",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "5",
    itemOneVotes: 4,
    itemTwoId: "1",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "3",
    itemOneVotes: 0,
    itemTwoId: "5",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "5",
    itemOneVotes: 1,
    itemTwoId: "2",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "6",
    itemOneVotes: 1,
    itemTwoId: "1",
    itemTwoVotes: 2,
  },
  {
    createdAt: new Date(),
    itemOneId: "7",
    itemOneVotes: 1,
    itemTwoId: "1",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "2",
    itemOneVotes: 1,
    itemTwoId: "1",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "6",
    itemOneVotes: 1,
    itemTwoId: "4",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "2",
    itemOneVotes: 0,
    itemTwoId: "7",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "6",
    itemOneVotes: 1,
    itemTwoId: "5",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "7",
    itemOneVotes: 1,
    itemTwoId: "2",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "4",
    itemOneVotes: 0,
    itemTwoId: "3",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "2",
    itemOneVotes: 2,
    itemTwoId: "3",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "5",
    itemOneVotes: 1,
    itemTwoId: "4",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "1",
    itemOneVotes: 1,
    itemTwoId: "7",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "5",
    itemOneVotes: 1,
    itemTwoId: "7",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "4",
    itemOneVotes: 0,
    itemTwoId: "7",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "5",
    itemOneVotes: 1,
    itemTwoId: "6",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "7",
    itemOneVotes: 1,
    itemTwoId: "4",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "30",
    itemOneVotes: 1,
    itemTwoId: "1",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "66",
    itemOneVotes: 1,
    itemTwoId: "83",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "26",
    itemOneVotes: 1,
    itemTwoId: "19",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "51",
    itemOneVotes: 1,
    itemTwoId: "58",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "99",
    itemOneVotes: 0,
    itemTwoId: "5",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "30",
    itemOneVotes: 1,
    itemTwoId: "96",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "56",
    itemOneVotes: 1,
    itemTwoId: "81",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "30",
    itemOneVotes: 1,
    itemTwoId: "75",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "49",
    itemOneVotes: 1,
    itemTwoId: "22",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "38",
    itemOneVotes: 0,
    itemTwoId: "30",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "24",
    itemOneVotes: 0,
    itemTwoId: "55",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "52",
    itemOneVotes: 1,
    itemTwoId: "94",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "77",
    itemOneVotes: 1,
    itemTwoId: "32",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "44",
    itemOneVotes: 1,
    itemTwoId: "38",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "11",
    itemOneVotes: 1,
    itemTwoId: "77",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "57",
    itemOneVotes: 0,
    itemTwoId: "31",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "15",
    itemOneVotes: 0,
    itemTwoId: "55",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "22",
    itemOneVotes: 0,
    itemTwoId: "69",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "73",
    itemOneVotes: 0,
    itemTwoId: "40",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "53",
    itemOneVotes: 0,
    itemTwoId: "55",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "74",
    itemOneVotes: 1,
    itemTwoId: "76",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "87",
    itemOneVotes: 0,
    itemTwoId: "7",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "24",
    itemOneVotes: 0,
    itemTwoId: "52",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "30",
    itemOneVotes: 1,
    itemTwoId: "69",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "70",
    itemOneVotes: 0,
    itemTwoId: "5",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "46",
    itemOneVotes: 1,
    itemTwoId: "51",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "26",
    itemOneVotes: 1,
    itemTwoId: "76",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "51",
    itemOneVotes: 0,
    itemTwoId: "11",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "4",
    itemOneVotes: 0,
    itemTwoId: "31",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "89",
    itemOneVotes: 0,
    itemTwoId: "45",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "70",
    itemOneVotes: 1,
    itemTwoId: "21",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "6",
    itemOneVotes: 1,
    itemTwoId: "33",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "5",
    itemOneVotes: 1,
    itemTwoId: "50",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "45",
    itemOneVotes: 0,
    itemTwoId: "14",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "94",
    itemOneVotes: 0,
    itemTwoId: "14",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "95",
    itemOneVotes: 0,
    itemTwoId: "62",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "6",
    itemOneVotes: 1,
    itemTwoId: "45",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "13",
    itemOneVotes: 1,
    itemTwoId: "80",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "64",
    itemOneVotes: 1,
    itemTwoId: "95",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "99",
    itemOneVotes: 1,
    itemTwoId: "83",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "81",
    itemOneVotes: 0,
    itemTwoId: "36",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "100",
    itemOneVotes: 0,
    itemTwoId: "57",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "52",
    itemOneVotes: 1,
    itemTwoId: "60",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "50",
    itemOneVotes: 1,
    itemTwoId: "89",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "83",
    itemOneVotes: 0,
    itemTwoId: "96",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "76",
    itemOneVotes: 0,
    itemTwoId: "57",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "85",
    itemOneVotes: 1,
    itemTwoId: "73",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "37",
    itemOneVotes: 1,
    itemTwoId: "34",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "64",
    itemOneVotes: 1,
    itemTwoId: "26",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "12",
    itemOneVotes: 0,
    itemTwoId: "69",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "25",
    itemOneVotes: 0,
    itemTwoId: "94",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "7",
    itemOneVotes: 0,
    itemTwoId: "34",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "27",
    itemOneVotes: 1,
    itemTwoId: "92",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "11",
    itemOneVotes: 0,
    itemTwoId: "61",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "96",
    itemOneVotes: 1,
    itemTwoId: "33",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "100",
    itemOneVotes: 1,
    itemTwoId: "90",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "31",
    itemOneVotes: 1,
    itemTwoId: "25",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "7",
    itemOneVotes: 0,
    itemTwoId: "14",
    itemTwoVotes: 2,
  },
  {
    createdAt: new Date(),
    itemOneId: "13",
    itemOneVotes: 1,
    itemTwoId: "4",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "17",
    itemOneVotes: 1,
    itemTwoId: "15",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "20",
    itemOneVotes: 0,
    itemTwoId: "6",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "15",
    itemOneVotes: 1,
    itemTwoId: "17",
    itemTwoVotes: 2,
  },
  {
    createdAt: new Date(),
    itemOneId: "6",
    itemOneVotes: 0,
    itemTwoId: "17",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "5",
    itemOneVotes: 1,
    itemTwoId: "17",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "11",
    itemOneVotes: 2,
    itemTwoId: "18",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "14",
    itemOneVotes: 1,
    itemTwoId: "4",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "11",
    itemOneVotes: 0,
    itemTwoId: "5",
    itemTwoVotes: 3,
  },
  {
    createdAt: new Date(),
    itemOneId: "20",
    itemOneVotes: 0,
    itemTwoId: "3",
    itemTwoVotes: 2,
  },
  {
    createdAt: new Date(),
    itemOneId: "17",
    itemOneVotes: 0,
    itemTwoId: "1",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "11",
    itemOneVotes: 1,
    itemTwoId: "6",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "13",
    itemOneVotes: 1,
    itemTwoId: "2",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "20",
    itemOneVotes: 0,
    itemTwoId: "1",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "18",
    itemOneVotes: 0,
    itemTwoId: "17",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "20",
    itemOneVotes: 0,
    itemTwoId: "17",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "2",
    itemOneVotes: 0,
    itemTwoId: "17",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "13",
    itemOneVotes: 1,
    itemTwoId: "20",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "20",
    itemOneVotes: 0,
    itemTwoId: "18",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "17",
    itemOneVotes: 1,
    itemTwoId: "6",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "18",
    itemOneVotes: 1,
    itemTwoId: "18",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "13",
    itemOneVotes: 1,
    itemTwoId: "18",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "17",
    itemOneVotes: 1,
    itemTwoId: "18",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "1",
    itemOneVotes: 1,
    itemTwoId: "12",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "2",
    itemOneVotes: 1,
    itemTwoId: "20",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "17",
    itemOneVotes: 1,
    itemTwoId: "20",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "3",
    itemOneVotes: 2,
    itemTwoId: "12",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "18",
    itemOneVotes: 0,
    itemTwoId: "7",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "20",
    itemOneVotes: 0,
    itemTwoId: "5",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "16",
    itemOneVotes: 0,
    itemTwoId: "2",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "11",
    itemOneVotes: 1,
    itemTwoId: "13",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "20",
    itemOneVotes: 0,
    itemTwoId: "2",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "16",
    itemOneVotes: 2,
    itemTwoId: "3",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "14",
    itemOneVotes: 2,
    itemTwoId: "2",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "2",
    itemOneVotes: 1,
    itemTwoId: "11",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "6",
    itemOneVotes: 0,
    itemTwoId: "18",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "1",
    itemOneVotes: 1,
    itemTwoId: "15",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "14",
    itemOneVotes: 1,
    itemTwoId: "6",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "5",
    itemOneVotes: 1,
    itemTwoId: "15",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "15",
    itemOneVotes: 1,
    itemTwoId: "20",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "14",
    itemOneVotes: 1,
    itemTwoId: "11",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "15",
    itemOneVotes: 0,
    itemTwoId: "1",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "11",
    itemOneVotes: 0,
    itemTwoId: "14",
    itemTwoVotes: 3,
  },
  {
    createdAt: new Date(),
    itemOneId: "11",
    itemOneVotes: 1,
    itemTwoId: "16",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "14",
    itemOneVotes: 1,
    itemTwoId: "16",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "2",
    itemOneVotes: 1,
    itemTwoId: "2",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "2",
    itemOneVotes: 1,
    itemTwoId: "16",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "12",
    itemOneVotes: 0,
    itemTwoId: "20",
    itemTwoVotes: 2,
  },
  {
    createdAt: new Date(),
    itemOneId: "1",
    itemOneVotes: 1,
    itemTwoId: "11",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "3",
    itemOneVotes: 0,
    itemTwoId: "17",
    itemTwoVotes: 2,
  },
  {
    createdAt: new Date(),
    itemOneId: "20",
    itemOneVotes: 2,
    itemTwoId: "12",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "18",
    itemOneVotes: 0,
    itemTwoId: "4",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "6",
    itemOneVotes: 1,
    itemTwoId: "11",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "13",
    itemOneVotes: 1,
    itemTwoId: "14",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "13",
    itemOneVotes: 2,
    itemTwoId: "6",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "18",
    itemOneVotes: 0,
    itemTwoId: "1",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "2",
    itemOneVotes: 0,
    itemTwoId: "13",
    itemTwoVotes: 3,
  },
  {
    createdAt: new Date(),
    itemOneId: "7",
    itemOneVotes: 1,
    itemTwoId: "11",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "11",
    itemOneVotes: 0,
    itemTwoId: "1",
    itemTwoVotes: 2,
  },
  {
    createdAt: new Date(),
    itemOneId: "5",
    itemOneVotes: 1,
    itemTwoId: "14",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "11",
    itemOneVotes: 1,
    itemTwoId: "20",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "13",
    itemOneVotes: 1,
    itemTwoId: "16",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "19",
    itemOneVotes: 0,
    itemTwoId: "17",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "19",
    itemOneVotes: 0,
    itemTwoId: "1",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "3",
    itemOneVotes: 1,
    itemTwoId: "15",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "18",
    itemOneVotes: 2,
    itemTwoId: "11",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "13",
    itemOneVotes: 1,
    itemTwoId: "7",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "5",
    itemOneVotes: 1,
    itemTwoId: "19",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "14",
    itemOneVotes: 1,
    itemTwoId: "7",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "6",
    itemOneVotes: 1,
    itemTwoId: "20",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "14",
    itemOneVotes: 1,
    itemTwoId: "5",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "7",
    itemOneVotes: 1,
    itemTwoId: "20",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "13",
    itemOneVotes: 0,
    itemTwoId: "11",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "7",
    itemOneVotes: 1,
    itemTwoId: "17",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "12",
    itemOneVotes: 0,
    itemTwoId: "3",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "3",
    itemOneVotes: 2,
    itemTwoId: "11",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "17",
    itemOneVotes: 1,
    itemTwoId: "13",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "18",
    itemOneVotes: 0,
    itemTwoId: "2",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "17",
    itemOneVotes: 0,
    itemTwoId: "5",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "12",
    itemOneVotes: 0,
    itemTwoId: "5",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "14",
    itemOneVotes: 1,
    itemTwoId: "20",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "11",
    itemOneVotes: 2,
    itemTwoId: "12",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "14",
    itemOneVotes: 0,
    itemTwoId: "1",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "19",
    itemOneVotes: 0,
    itemTwoId: "6",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "14",
    itemOneVotes: 1,
    itemTwoId: "3",
    itemTwoVotes: 2,
  },
  {
    createdAt: new Date(),
    itemOneId: "6",
    itemOneVotes: 1,
    itemTwoId: "14",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "18",
    itemOneVotes: 0,
    itemTwoId: "13",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "15",
    itemOneVotes: 0,
    itemTwoId: "11",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "11",
    itemOneVotes: 1,
    itemTwoId: "7",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "19",
    itemOneVotes: 0,
    itemTwoId: "2",
    itemTwoVotes: 3,
  },
  {
    createdAt: new Date(),
    itemOneId: "16",
    itemOneVotes: 0,
    itemTwoId: "14",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "15",
    itemOneVotes: 0,
    itemTwoId: "3",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "20",
    itemOneVotes: 1,
    itemTwoId: "19",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "20",
    itemOneVotes: 1,
    itemTwoId: "13",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "19",
    itemOneVotes: 0,
    itemTwoId: "11",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "6",
    itemOneVotes: 1,
    itemTwoId: "7",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "12",
    itemOneVotes: 0,
    itemTwoId: "19",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "19",
    itemOneVotes: 1,
    itemTwoId: "12",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "14",
    itemOneVotes: 3,
    itemTwoId: "13",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "13",
    itemOneVotes: 0,
    itemTwoId: "19",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "15",
    itemOneVotes: 0,
    itemTwoId: "5",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "16",
    itemOneVotes: 0,
    itemTwoId: "15",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "3",
    itemOneVotes: 0,
    itemTwoId: "2",
    itemTwoVotes: 2,
  },
  {
    createdAt: new Date(),
    itemOneId: "11",
    itemOneVotes: 1,
    itemTwoId: "15",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "2",
    itemOneVotes: 0,
    itemTwoId: "15",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "13",
    itemOneVotes: 2,
    itemTwoId: "12",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "15",
    itemOneVotes: 1,
    itemTwoId: "2",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "1",
    itemOneVotes: 0,
    itemTwoId: "13",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "13",
    itemOneVotes: 1,
    itemTwoId: "15",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "19",
    itemOneVotes: 0,
    itemTwoId: "16",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "2",
    itemOneVotes: 1,
    itemTwoId: "19",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "16",
    itemOneVotes: 0,
    itemTwoId: "6",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "12",
    itemOneVotes: 0,
    itemTwoId: "17",
    itemTwoVotes: 2,
  },
  {
    createdAt: new Date(),
    itemOneId: "2",
    itemOneVotes: 1,
    itemTwoId: "12",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "12",
    itemOneVotes: 0,
    itemTwoId: "18",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "12",
    itemOneVotes: 0,
    itemTwoId: "6",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "17",
    itemOneVotes: 1,
    itemTwoId: "16",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "3",
    itemOneVotes: 0,
    itemTwoId: "16",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "20",
    itemOneVotes: 1,
    itemTwoId: "14",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "3",
    itemOneVotes: 1,
    itemTwoId: "14",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "7",
    itemOneVotes: 1,
    itemTwoId: "19",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "16",
    itemOneVotes: 0,
    itemTwoId: "12",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "12",
    itemOneVotes: 0,
    itemTwoId: "1",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "3",
    itemOneVotes: 1,
    itemTwoId: "18",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "11",
    itemOneVotes: 0,
    itemTwoId: "17",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "2",
    itemOneVotes: 1,
    itemTwoId: "14",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "254",
    itemOneVotes: 1,
    itemTwoId: "96",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "749",
    itemOneVotes: 1,
    itemTwoId: "971",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "376",
    itemOneVotes: 0,
    itemTwoId: "176",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "84",
    itemOneVotes: 0,
    itemTwoId: "411",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "928",
    itemOneVotes: 0,
    itemTwoId: "960",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "79",
    itemOneVotes: 1,
    itemTwoId: "103",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "352",
    itemOneVotes: 1,
    itemTwoId: "370",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "325",
    itemOneVotes: 1,
    itemTwoId: "425",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "863",
    itemOneVotes: 0,
    itemTwoId: "456",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "564",
    itemOneVotes: 1,
    itemTwoId: "758",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "682",
    itemOneVotes: 1,
    itemTwoId: "186",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "885",
    itemOneVotes: 1,
    itemTwoId: "829",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "563",
    itemOneVotes: 0,
    itemTwoId: "309",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "995",
    itemOneVotes: 1,
    itemTwoId: "969",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "582",
    itemOneVotes: 0,
    itemTwoId: "380",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "482",
    itemOneVotes: 1,
    itemTwoId: "325",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "744",
    itemOneVotes: 0,
    itemTwoId: "242",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "604",
    itemOneVotes: 0,
    itemTwoId: "476",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "557",
    itemOneVotes: 1,
    itemTwoId: "720",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "240",
    itemOneVotes: 0,
    itemTwoId: "774",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "213",
    itemOneVotes: 1,
    itemTwoId: "939",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "246",
    itemOneVotes: 1,
    itemTwoId: "473",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "832",
    itemOneVotes: 1,
    itemTwoId: "700",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "599",
    itemOneVotes: 0,
    itemTwoId: "331",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "721",
    itemOneVotes: 0,
    itemTwoId: "176",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "611",
    itemOneVotes: 0,
    itemTwoId: "929",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "161",
    itemOneVotes: 1,
    itemTwoId: "645",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "157",
    itemOneVotes: 0,
    itemTwoId: "535",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "713",
    itemOneVotes: 0,
    itemTwoId: "47",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "689",
    itemOneVotes: 1,
    itemTwoId: "382",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "800",
    itemOneVotes: 0,
    itemTwoId: "213",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "926",
    itemOneVotes: 0,
    itemTwoId: "520",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "400",
    itemOneVotes: 0,
    itemTwoId: "170",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "652",
    itemOneVotes: 1,
    itemTwoId: "721",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "51",
    itemOneVotes: 1,
    itemTwoId: "432",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "976",
    itemOneVotes: 1,
    itemTwoId: "466",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "598",
    itemOneVotes: 0,
    itemTwoId: "328",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "18",
    itemOneVotes: 0,
    itemTwoId: "511",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "976",
    itemOneVotes: 1,
    itemTwoId: "20",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "877",
    itemOneVotes: 0,
    itemTwoId: "365",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "212",
    itemOneVotes: 1,
    itemTwoId: "515",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "189",
    itemOneVotes: 0,
    itemTwoId: "61",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "438",
    itemOneVotes: 1,
    itemTwoId: "155",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "242",
    itemOneVotes: 0,
    itemTwoId: "466",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "918",
    itemOneVotes: 1,
    itemTwoId: "147",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "525",
    itemOneVotes: 1,
    itemTwoId: "399",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "120",
    itemOneVotes: 1,
    itemTwoId: "816",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "44",
    itemOneVotes: 1,
    itemTwoId: "876",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "621",
    itemOneVotes: 0,
    itemTwoId: "897",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "647",
    itemOneVotes: 0,
    itemTwoId: "394",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "357",
    itemOneVotes: 1,
    itemTwoId: "395",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "859",
    itemOneVotes: 1,
    itemTwoId: "872",
    itemTwoVotes: 0,
  },
  {
    createdAt: new Date(),
    itemOneId: "922",
    itemOneVotes: 0,
    itemTwoId: "103",
    itemTwoVotes: 1,
  },
  {
    createdAt: new Date(),
    itemOneId: "860",
    itemOneVotes: 0,
    itemTwoId: "208",
    itemTwoVotes: 1,
  },
];

export { battles, items, users };
